backend: "onnxruntime"
max_batch_size : 0
input [
  {
    name: "kpts0"
    data_type: TYPE_FP32
    dims: [ 1, 512, 2 ]
  },
  {
    name: "kpts1"
    data_type: TYPE_FP32
    dims: [ 1, 512, 2 ]
  },
  {
    name: "desc0"
    data_type: TYPE_FP32
    dims: [ 1, 512, 256 ]
  },
  {
    name: "desc1"
    data_type: TYPE_FP32
    dims: [ 1, 512, 256 ]
  },
  {
    name: "mask0"
    data_type: TYPE_BOOL
    dims: [ 1, 512, 1 ]
  },
  {
    name: "mask1"
    data_type: TYPE_BOOL
    dims: [ 1, 512, 1 ]
  },
  {
    name: "img_shape0"
    data_type: TYPE_INT32
    dims: [1, 2]
  },
  {
    name: "img_shape1"
    data_type: TYPE_INT32
    dims: [1, 2]
  },
  {
    name: "threshold"
    data_type: TYPE_FP32
    dims: [1, 1]
  }
]
output [
  {
    name: "match_indices"
    data_type: TYPE_INT32
    dims: [ 1, 512]
  },
  {
    name: "score"
    data_type: TYPE_FP32
    dims: [ 1, 512]
  }
]

default_model_filename: "lightglue_fp16.onnx"
